airports = {
"Guangzhou Baiyun International Airport": 'ZGGG',
"Hartsfield–Jackson Atlanta International Airport": 'KATL',
"Chengdu Shuangliu International Airport": 'ZUUU',
"Dallas/Fort Worth International Airport": 'KDFW',
"Shenzhen Bao'an International Airport": 'ZGSZ',
"Chongqing Jiangbei International Airport": 'ZUCK',
"Beijing Capital International Airport": 'ZBAA',
"Denver International Airport": 'KDEN',
"Kunming Changshui International Airport": 'ZPPP',
"Shanghai Hongqiao International Airport": 'ZSSS',
"Xi'an Xianyang International Airport": 'ZLXY',
"Tokyo Haneda Airport": 'RJTT',
"O'Hare International Airport": 'KORD',
"Shanghai Pudong International Airport": 'ZSPD',
"Los Angeles International Airport": 'KLAX',
"Indira Gandhi International Airport": 'VIDP',
"Hangzhou Xiaoshan International Airport": 'ZSHC',
"Charlotte Douglas International Airport": 'KCLT',
"Dubai International Airport": 'OMDB',
"Istanbul Airport": 'LTFM',
"Charles de Gaulle Airport": 'LFPG',
"Heathrow Airport": 'EGLL',
"Mexico City International Airport": 'MMMX',
"Phoenix Sky Harbor International Airport": 'KPHX',
"Tan Son Nhat International Airport": 'VVTS',
"Orlando International Airport": 'KMCO',
"Zhengzhou Xinzheng International Airport": 'ZHCC',
"Jeju International Airport": 'RKPC',
"Amsterdam Airport Schiphol": 'EHAM',
"São Paulo/Guarulhos International Airport": 'SBGR',
"Seattle–Tacoma International Airport": 'KSEA',
"Nanjing Lukou International Airport": 'ZSNJ',
"Sheremetyevo International Airport": 'UUEE',
"Changsha Huanghua International Airport": 'ZGHA',
"Frankfurt Airport": 'EDDF',
"Miami International Airport": 'KMIA',
"George Bush Intercontinental Airport": 'KIAH',
"Gimpo International Airport": 'RKSS',
"Madrid Barajas Airport": 'LEMD',
"Istanbul Sabiha Gökçen International Airport": 'LTFJ',
"Xiamen Gaoqi International Airport": 'ZSAM',
"Suvarnabhumi Airport": 'VTBS',
"John F. Kennedy International Airport": 'KJFK',
"Guiyang Longdongbao International Airport": 'ZUGY',
"Haikou Meilan International Airport": 'ZJHK',
"Fort Lauderdale–Hollywood International Airport": 'KFLL',
"San Francisco International Airport": 'KSFO',
"Moscow Domodedovo Airport": 'UUDD',
"Beijing Daxing International Airport": 'ZBAD',
"Newark Liberty International Airport": 'KEWR'
}
